### PR TITLE
Added support for Farsi, show support for custom templates

### PR DESCRIPTION
**Pull request by AmirAsghary**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
Does not support Farsi/Persian (fa)
Does not show support for custom templates

* **What is the new behavior (if this is a feature change)?**
Now supports Farsi/Persian (fa)
Shows support for custom templates

* **Other information**:

### CODE REVIEW

**Comment by phodal** [comment]
@AmirAsghary would you like to remove unneed changes in package.json? It cannot publish it this package.

**Comment by AmirAsghary** [comment]
oh yeah. my bad.

**Comment by AmirAsghary** [comment]
@phodal fixed.

**Comment by phodal** [comment]
Sorry, I forgot to write in README.md about create a `fa.md` in `src/lib/templates`

**Comment by AmirAsghary** [comment]
template was added.

**Comment by phodal** [comment]
Thanks @AmirAsghary .  already publish to npm, you can try it now.

**Pull request merged**
